# Generated by Django 4.1.6 on 2023-06-11 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('linked_in_profile_url', models.URLField()),
                ('is_objective_filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=50)),
                ('job_itle', models.CharField(max_length=100)),
                ('employment_dates', models.CharField(max_length=20)),
                ('job_responsibilities', models.TextField()),
                ('accomplishments', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.TextField()),
                ('soft', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_a', models.CharField(max_length=200)),
                ('reference_b', models.CharField(max_length=200)),
                ('reference_c', models.CharField(max_length=200)),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_affiliations', models.CharField(max_length=200)),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('involvement_dates', models.CharField(max_length=20)),
                ('responsibilities', models.TextField()),
                ('accomplishments', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=20)),
                ('graduation_date', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=100)),
                ('gpa', models.FloatField(default=0)),
                ('coursework', models.CharField(max_length=200)),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=200)),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField()),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.personalinfo')),
            ],
        ),
    ]
