# Generated by Django 4.1.6 on 2023-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_education_personal_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='is_objective_filled',
            new_name='is_additional_information_clicked',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_award_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_education_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_internship_experience_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_job_description_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_objective_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_professional_affiliation_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_refrence_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_skill_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_work_experience_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
