# Generated by Django 3.2.13 on 2023-07-18 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_rename_is_objective_filled_personalinfo_is_additional_information_clicked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
                ('resume', models.TextField()),
            ],
        ),
    ]
